#!/bin/bash
# Machine profile: load, validate and derive settings from a config file.
# Shared by the installer and host-side tests. INSTALL_PROFILE_ERROR is read
# by callers after a failed load.
# shellcheck disable=SC2034

INSTALL_PROFILE_VARS="DISK HOSTNAME USERNAME USER_GROUPS TIMEZONE KEYMAP LOCALE \
LIBC MIRROR ESP_SIZE_MIB BTRFS_OPTS SUBVOLUMES PACKAGES SERVICES"

# Sources $1 and sets REPO_URL, ARCH, ESP_DEV, ROOT_DEV and a canonical DISK.
install_profile_load() {
  local config=$1 setting canonical_disk subvol mountpoint

  INSTALL_PROFILE_ERROR=

  if [ ! -f "$config" ]; then
    INSTALL_PROFILE_ERROR="config not found: $config"
    return 1
  fi
  # shellcheck source=/dev/null
  . "$config"

  for setting in $INSTALL_PROFILE_VARS; do
    [ "$setting" = LOCALE ] && continue
    if [ -z "${!setting:-}" ]; then
      INSTALL_PROFILE_ERROR="$setting is not set in $config"
      return 1
    fi
  done

  case "$LIBC" in
    glibc)
      if [ -z "${LOCALE:-}" ]; then
        INSTALL_PROFILE_ERROR="LOCALE is not set in $config"
        return 1
      fi
      REPO_URL="$MIRROR/current"
      ARCH="x86_64"
      ;;
    musl)
      REPO_URL="$MIRROR/current/musl"
      ARCH="x86_64-musl"
      ;;
    *)
      INSTALL_PROFILE_ERROR="LIBC must be glibc or musl, got: $LIBC"
      return 1
      ;;
  esac

  read -r subvol mountpoint < <(install_profile_subvolumes)
  if [ "$mountpoint" != "/" ]; then
    INSTALL_PROFILE_ERROR="first SUBVOLUMES entry must mount at /"
    return 1
  fi

  if ! canonical_disk="$(readlink -f -- "$DISK")" || [ -z "$canonical_disk" ]; then
    INSTALL_PROFILE_ERROR="could not canonicalize DISK: $DISK"
    return 1
  fi
  DISK="$canonical_disk"

  # nvme0n1 -> nvme0n1p1; sda -> sda1
  case "$DISK" in
    *[0-9]) ESP_DEV="${DISK}p1"; ROOT_DEV="${DISK}p2" ;;
    *)      ESP_DEV="${DISK}1";  ROOT_DEV="${DISK}2" ;;
  esac
}

# Prints one "name mountpoint" line per SUBVOLUMES entry, in config order.
install_profile_subvolumes() {
  local pair

  for pair in $SUBVOLUMES; do
    printf '%s %s\n' "${pair%%=*}" "${pair#*=}"
  done
}

# Prints /etc/fstab for the loaded profile.
install_profile_fstab() {
  local root_uuid=$1 esp_uuid=$2 subvol mountpoint

  echo "# generated by install.sh"
  while read -r subvol mountpoint; do
    echo "UUID=$root_uuid $mountpoint btrfs $BTRFS_OPTS,subvol=$subvol 0 0"
  done < <(install_profile_subvolumes)
  echo "UUID=$esp_uuid /boot/efi vfat defaults 0 2"
  echo "tmpfs /tmp tmpfs defaults,nosuid,nodev 0 0"
}

# Prints the resolved settings as a sourceable env file.
install_profile_dump() {
  local name

  for name in $INSTALL_PROFILE_VARS; do
    printf '%s=%q\n' "$name" "${!name:-}"
  done
}
