#!/bin/bash
# ─────────────────────────────────────────────────────────────────────
# install.sh — deterministic Void Linux install (UEFI + btrfs)
#
# Run as root from the official Void live ISO:
#   ./scripts/install.sh config/default.env
#
# Wipes $DISK entirely: GPT with an ESP + a btrfs partition with
# subvolumes, bootstraps base-system via xbps into /mnt, then chroots
# in and runs configure.sh.
#
# Safety: refuses to run without FORCE=1 or an interactive "yes".
# ─────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TARGET=/mnt

log() { printf '\033[1;32m==>\033[0m %s\n' "$*"; }
die() { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

# ── Preflight ────────────────────────────────────────────────────────

CONFIG="${1:-}"
[ -n "$CONFIG" ] || die "usage: $0 <config.env>"
[ -f "$CONFIG" ] || die "config not found: $CONFIG"
# shellcheck source=/dev/null
. "$CONFIG"

[ "$(id -u)" -eq 0 ] || die "must run as root"
[ -n "${DISK:-}" ] || die "DISK is not set in $CONFIG"
[ -b "$DISK" ] || die "DISK is not a block device: $DISK"
[ -d /sys/firmware/efi ] || die "not booted in UEFI mode"

for cmd in sfdisk mkfs.vfat mkfs.btrfs xbps-install blkid wipefs; do
  command -v "$cmd" >/dev/null || die "missing command: $cmd"
done

case "$LIBC" in
  glibc) REPO_URL="$MIRROR/current" ;;
  musl)  REPO_URL="$MIRROR/current/musl" ;;
  *)     die "LIBC must be glibc or musl, got: $LIBC" ;;
esac
ARCH="x86_64"
[ "$LIBC" = "musl" ] && ARCH="x86_64-musl"

log "Target disk : $DISK"
log "libc        : $LIBC ($REPO_URL)"
log "Hostname    : $HOSTNAME"
sfdisk -l "$DISK" | sed -n '1,4p' || true

if [ "${FORCE:-0}" != "1" ]; then
  printf '\033[1;31mThis will DESTROY ALL DATA on %s. Type "yes" to continue: \033[0m' "$DISK"
  read -r answer
  [ "$answer" = "yes" ] || die "aborted"
fi

# Prompt for passwords now (before the long install) if not preset.
if [ -z "${ROOT_PASSWORD:-}" ]; then
  read -rsp "root password: " ROOT_PASSWORD; echo
  read -rsp "root password (again): " confirm; echo
  [ "$ROOT_PASSWORD" = "$confirm" ] || die "passwords do not match"
fi
if [ -z "${USER_PASSWORD:-}" ]; then
  read -rsp "password for $USERNAME: " USER_PASSWORD; echo
  read -rsp "password for $USERNAME (again): " confirm; echo
  [ "$USER_PASSWORD" = "$confirm" ] || die "passwords do not match"
fi

# ── Partition ────────────────────────────────────────────────────────

log "Wiping and partitioning $DISK"
umount -R "$TARGET" 2>/dev/null || true
wipefs -af "$DISK"
sfdisk "$DISK" <<EOF
label: gpt
size=${ESP_SIZE_MIB}MiB, type=uefi, name=ESP
type=linux, name=void
EOF
# Let the kernel settle and pick up the new partition table.
command -v partprobe >/dev/null && partprobe "$DISK" || true
sleep 1

# Handle both /dev/sda1 and /dev/nvme0n1p1 style names.
part() {
  if [ -b "${DISK}$1" ]; then echo "${DISK}$1"; else echo "${DISK}p$1"; fi
}
ESP_DEV="$(part 1)"
ROOT_DEV="$(part 2)"
[ -b "$ESP_DEV" ] && [ -b "$ROOT_DEV" ] || die "partitions did not appear"

# ── Filesystems + subvolumes ─────────────────────────────────────────

log "Creating filesystems"
mkfs.vfat -F32 -n ESP "$ESP_DEV"
mkfs.btrfs -f -L void "$ROOT_DEV"

log "Creating btrfs subvolumes: $SUBVOLUMES"
mount "$ROOT_DEV" "$TARGET"
for pair in $SUBVOLUMES; do
  btrfs subvolume create "$TARGET/${pair%%=*}"
done
umount "$TARGET"

log "Mounting target tree"
# Mount subvolumes in config order; '@=/' must come first.
for pair in $SUBVOLUMES; do
  subvol="${pair%%=*}" mountpoint="${pair#*=}"
  mkdir -p "$TARGET$mountpoint"
  mount -o "$BTRFS_OPTS,subvol=$subvol" "$ROOT_DEV" "$TARGET$mountpoint"
done
mkdir -p "$TARGET/boot/efi"
mount "$ESP_DEV" "$TARGET/boot/efi"

# ── Bootstrap base system ────────────────────────────────────────────

log "Installing packages into $TARGET (this downloads from $REPO_URL)"
mkdir -p "$TARGET/var/db/xbps/keys"
cp /var/db/xbps/keys/* "$TARGET/var/db/xbps/keys/"
# shellcheck disable=SC2086
XBPS_ARCH="$ARCH" xbps-install -Sy -R "$REPO_URL" -r "$TARGET" $PACKAGES

# ── fstab ────────────────────────────────────────────────────────────

log "Writing /etc/fstab"
ROOT_UUID="$(blkid -s UUID -o value "$ROOT_DEV")"
ESP_UUID="$(blkid -s UUID -o value "$ESP_DEV")"
{
  echo "# generated by install.sh"
  for pair in $SUBVOLUMES; do
    subvol="${pair%%=*}" mountpoint="${pair#*=}"
    echo "UUID=$ROOT_UUID $mountpoint btrfs $BTRFS_OPTS,subvol=$subvol 0 0"
  done
  echo "UUID=$ESP_UUID /boot/efi vfat defaults 0 2"
  echo "tmpfs /tmp tmpfs defaults,nosuid,nodev 0 0"
} > "$TARGET/etc/fstab"

# ── Chroot configuration ─────────────────────────────────────────────

log "Entering chroot to configure"
for fs in dev proc sys; do
  mount --rbind "/$fs" "$TARGET/$fs"
  mount --make-rslave "$TARGET/$fs"
done
mount -t efivarfs efivarfs "$TARGET/sys/firmware/efi/efivars" 2>/dev/null || true
cp /etc/resolv.conf "$TARGET/etc/resolv.conf"

install -Dm755 "$SCRIPT_DIR/configure.sh" "$TARGET/root/configure.sh"
install -Dm644 "$CONFIG" "$TARGET/root/install.env"
# Pass secrets via file, not argv (argv is visible in ps).
{
  printf 'ROOT_PASSWORD=%q\n' "$ROOT_PASSWORD"
  printf 'USER_PASSWORD=%q\n' "$USER_PASSWORD"
} > "$TARGET/root/install.secrets"
chmod 600 "$TARGET/root/install.secrets"

chroot "$TARGET" /root/configure.sh

rm -f "$TARGET/root/configure.sh" "$TARGET/root/install.env" \
      "$TARGET/root/install.secrets"

# ── Teardown ─────────────────────────────────────────────────────────

log "Unmounting"
umount -R "$TARGET"

log "Done. Reboot into the new system (remove the live medium)."
